export const menuData = [
    {
        id: '1',
        title: 'Dashboard',
        img: './icons/home.svg',
        isActiveMenuItem: false,
        isMessage: false,
    },
    {
        id: '2',
        title: 'Executions',
        img: './icons/line_chart.svg',
        isActiveMenuItem: false,
        isMessage: false,
    },
    {
        id: '3',
        title: 'Workouts',
        img: './icons/stopwatch.svg',
        isActiveMenuItem: false,
        isMessage: true,
    },
    {
        id: '4',
        title: 'Programs',
        img: './icons/bar_chart.svg',
        isActiveMenuItem: true,
        isMessage: false,
    },
    {
        id: '5',
        title: 'Teams',
        img: './icons/users.svg',
        isActiveMenuItem: false,
        isMessage: false,
    },
    {
        id: '6',
        title: 'Players',
        img: './icons/user.svg',
        isActiveMenuItem: false,
        isMessage: false,
    },
    {
        id: '7',
        title: 'Settings',
        img: './icons/settings.svg',
        isActiveMenuItem: false,
        isMessage: false,
    },
];
